### ISSUE TITLE
Infinite Loop When Running Graph Operations Option 5

### ISSUE THREAD

**Issue by JakeC1020** [dingjunweng/Weng_Liu_CSCI2270_FinalProject#1]
When I was attempting to break the code, I found that the in the Graph Operations program, "Find a path with limited distance" can cause an infinite loop when gibberish is entered into the program. For example, for the starting vertex I entered "abcdefg", for a destination vertex, I entered "abcdefg", and for a distance limit I entered "abcdefg". The program then appears to print the Graph Operations menu over and over until I force quit out of the program.

This appears to be in the limitedDistancePath() function. Based on the fact that you check to make sure that the vertices are found, my guess is that the distance parameter is not being validated enough, and by making sure that this is a reasonable numerical value, the issue should be fixed.

**Comment by dingjunweng** [comment]
Hi Jake, thanks for the issue. I fixed it.
